version: '3'
services:
  portfolio:
    build:
      context: .
    image: netflix-clone:v1.0
    ports:
      - "8100:80"
    restart: unless-stopped
networks:
  default:
    external: true
    name: nginx-network